volumes:
    caddy_data:
    caddy_config:
    postgres_data:
    mailpit_data:

services:
    web:
        image: ghcr.io/thedevs-cz/php:8.3
        restart: unless-stopped
        tty: true
        volumes:
            - .:/app
            - ./.docker/docker-entrypoint.sh:/usr/local/bin/docker-php-entrypoint
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - postgres
        ports:
            - "8080:80"
        environment:
            XDEBUG_CONFIG: "client_host=host.docker.internal"
            XDEBUG_MODE: debug
            PHP_IDE_CONFIG: "serverName=localhost"
            SERVER_NAME: :80

    messenger-consumer:
        image: ghcr.io/thedevs-cz/php:8.3
        restart: unless-stopped
        command: "bash -c 'wait-for-it postgres:5432 -- sleep 15 && bin/console messenger:consume async -vv --time-limit 60 --memory-limit 128M'"
        volumes:
            - .:/app
            - ./.docker/docker-entrypoint.sh:/usr/local/bin/docker-php-entrypoint
        depends_on:
            - web
            - postgres
        environment:
            XDEBUG_CONFIG: "client_host=host.docker.internal"
            XDEBUG_MODE: debug
            PHP_IDE_CONFIG: "serverName=localhost"

    postgres:
        image: postgres:17.0
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: wms
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    adminer:
        image: adminer:4.8.0
        ports:
            - "8000:8080"
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        depends_on:
            - postgres

    mailer:
        image: axllent/mailpit
        ports:
            - "1025:1025"
            - "8025:8025"
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
            MP_DATABASE: "/data/mailpit.db"
        volumes:
            - mailpit_data:/data
